-- Taxonomy v2: generated by scripts/taxonomy-v2.ts. Data only; additive.

INSERT INTO tag_categories (slug, display_name, search_weight, sort_order) VALUES ('venue', 'Venue', 1.2, 1)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, search_weight = EXCLUDED.search_weight, sort_order = EXCLUDED.sort_order;
INSERT INTO tag_categories (slug, display_name, search_weight, sort_order) VALUES ('cuisine', 'Cuisine', 1.1, 2)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, search_weight = EXCLUDED.search_weight, sort_order = EXCLUDED.sort_order;
INSERT INTO tag_categories (slug, display_name, search_weight, sort_order) VALUES ('food', 'Food', 1.3, 3)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, search_weight = EXCLUDED.search_weight, sort_order = EXCLUDED.sort_order;
INSERT INTO tag_categories (slug, display_name, search_weight, sort_order) VALUES ('vibe', 'Vibe', 1, 4)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, search_weight = EXCLUDED.search_weight, sort_order = EXCLUDED.sort_order;
INSERT INTO tag_categories (slug, display_name, search_weight, sort_order) VALUES ('occasion', 'Occasion', 1, 5)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, search_weight = EXCLUDED.search_weight, sort_order = EXCLUDED.sort_order;
INSERT INTO tag_categories (slug, display_name, search_weight, sort_order) VALUES ('features', 'Features', 0.9, 6)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, search_weight = EXCLUDED.search_weight, sort_order = EXCLUDED.sort_order;
INSERT INTO tag_categories (slug, display_name, search_weight, sort_order) VALUES ('price', 'Price', 0.8, 7)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, search_weight = EXCLUDED.search_weight, sort_order = EXCLUDED.sort_order;
INSERT INTO tag_categories (slug, display_name, search_weight, sort_order) VALUES ('dietary', 'Dietary', 0.8, 8)
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, search_weight = EXCLUDED.search_weight, sort_order = EXCLUDED.sort_order;
UPDATE tag_categories SET sort_order = 100 + sort_order WHERE slug NOT IN ('venue', 'cuisine', 'food', 'vibe', 'occasion', 'features', 'price', 'dietary');

INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'restaurant', 'Restaurant', 'A sit-down or order-at-the-counter place whose main business is serving meals.', ARRAY['eatery', 'spot']::text[], 1, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'bar', 'Bar', 'A place whose main business is drinks, with or without food.', ARRAY['pub', 'tavern']::text[], 2, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'cocktail_bar', 'Cocktail Bar', 'A bar known for mixed drinks: creators talk about the cocktails or the bartending.', ARRAY['cocktails', 'speakeasy', 'mixology']::text[], 3, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'wine_bar', 'Wine Bar', 'A bar built around wine, including natural wine bars.', ARRAY['natural wine', 'wine']::text[], 4, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'dive_bar', 'Dive Bar', 'A cheap, unpretentious neighborhood bar.', ARRAY['dive']::text[], 5, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'cafe', 'Café', 'A coffee shop or café where coffee and light food are the draw.', ARRAY['coffee shop', 'coffeehouse']::text[], 6, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'bakery', 'Bakery', 'A shop that bakes and sells bread, pastries or cakes.', ARRAY['patisserie', 'boulangerie']::text[], 7, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'deli', 'Deli', 'A deli, bodega counter or sandwich shop that makes food to order.', ARRAY['bodega', 'sandwich shop']::text[], 8, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'food_hall', 'Food Hall', 'A hall or market with several independent food stalls under one roof.', ARRAY['food market', 'market']::text[], 9, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'dessert_shop', 'Dessert Shop', 'A shop whose main business is sweets: ice cream, cookies, doughnuts, candy or desserts.', ARRAY['sweets', 'ice cream shop', 'doughnut shop']::text[], 10, 'active' FROM tag_categories WHERE slug = 'venue'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'american', 'American', 'American food: burgers, diners, comfort food, new American menus.', ARRAY['new american', 'comfort food', 'diner']::text[], 1, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'italian', 'Italian', 'Italian food, including red-sauce joints and Italian-American.', ARRAY['italian-american', 'trattoria', 'osteria']::text[], 2, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'mexican', 'Mexican', 'Mexican food, including taquerias.', ARRAY['taqueria', 'tex-mex']::text[], 3, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'japanese', 'Japanese', 'Japanese food: sushi, ramen, izakaya, omakase and more.', ARRAY['izakaya', 'omakase']::text[], 4, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'chinese', 'Chinese', 'Chinese food of any region, including dim sum.', ARRAY['dim sum', 'cantonese', 'sichuan', 'szechuan']::text[], 5, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'korean', 'Korean', 'Korean food, including Korean barbecue and fried chicken.', ARRAY['kbbq', 'korean bbq']::text[], 6, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'thai', 'Thai', 'Thai food.', '{}'::text[], 7, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'vietnamese', 'Vietnamese', 'Vietnamese food, including pho and banh mi.', ARRAY['pho', 'banh mi']::text[], 8, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'indian', 'Indian', 'Indian and South Asian food.', ARRAY['south asian', 'pakistani', 'bangladeshi']::text[], 9, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'mediterranean', 'Mediterranean', 'Greek, Turkish, Levantine-leaning Mediterranean menus.', ARRAY['greek', 'turkish']::text[], 10, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'middle_eastern', 'Middle Eastern', 'Middle Eastern food: falafel, shawarma, mezze.', ARRAY['lebanese', 'israeli', 'falafel', 'shawarma']::text[], 11, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'french', 'French', 'French food, from bistros to fine dining.', ARRAY['bistro', 'brasserie']::text[], 12, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'caribbean', 'Caribbean', 'Caribbean food: Jamaican, Trinidadian, Puerto Rican, Dominican and more.', ARRAY['jamaican', 'puerto rican', 'dominican']::text[], 13, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'latin_american', 'Latin American', 'Central and South American food outside Mexico.', ARRAY['peruvian', 'colombian', 'argentinian', 'venezuelan']::text[], 14, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'jewish_deli', 'Jewish Deli', 'A Jewish deli or appetizing shop: pastrami, smoked fish, knishes.', ARRAY['appetizing', 'pastrami']::text[], 15, 'active' FROM tag_categories WHERE slug = 'cuisine'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'burger', 'Burger', 'The creator eats or recommends a burger here.', ARRAY['burgers', 'cheeseburger']::text[], 1, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'smashburger', 'Smashburger', 'A smashed, thin-patty burger with crispy edges.', ARRAY['smash burger', 'smashed burger']::text[], 2, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'pizza', 'Pizza', 'The creator eats or recommends pizza here.', ARRAY['slice', 'pie', 'detroit-style', 'grandma slice']::text[], 3, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'pasta', 'Pasta', 'The creator eats or recommends a pasta dish here.', ARRAY['rigatoni', 'spaghetti', 'cacio e pepe']::text[], 4, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'tacos', 'Tacos', 'The creator eats or recommends tacos here.', ARRAY['taco']::text[], 5, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'birria', 'Birria', 'Birria: stewed meat, usually as tacos with consommé for dipping.', ARRAY['birria tacos', 'quesabirria']::text[], 6, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'ramen', 'Ramen', 'Japanese ramen.', '{}'::text[], 7, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'sushi', 'Sushi', 'Sushi, sashimi or hand rolls.', ARRAY['omakase', 'hand roll']::text[], 8, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'wings', 'Wings', 'Chicken wings.', ARRAY['chicken wings', 'buffalo wings']::text[], 9, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'bbq', 'BBQ', 'Smoked, American-style barbecue.', ARRAY['barbecue', 'brisket', 'smokehouse']::text[], 10, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'sandwich', 'Sandwich', 'The creator eats or recommends a sandwich or hero here.', ARRAY['sandwiches', 'hero', 'sub', 'chopped cheese']::text[], 11, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'bagels', 'Bagels', 'Bagels, including bagel sandwiches.', ARRAY['bagel', 'bacon egg and cheese']::text[], 12, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'coffee', 'Coffee', 'Coffee drinks are part of the recommendation.', ARRAY['espresso', 'latte', 'matcha']::text[], 13, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'pastries', 'Pastries', 'Croissants, danishes, scones, cinnamon rolls and other baked pastries.', ARRAY['croissant', 'pastry', 'baked goods', 'cinnamon roll']::text[], 14, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'dessert', 'Dessert', 'A sweet course or treat: cake, pie, cookies, doughnuts.', ARRAY['desserts', 'cake', 'cookies', 'doughnuts', 'sweets']::text[], 15, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'ice_cream', 'Ice Cream', 'Ice cream, gelato, soft serve or frozen custard.', ARRAY['gelato', 'soft serve', 'frozen custard']::text[], 16, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'seafood', 'Seafood', 'Fish or shellfish is the draw: oysters, lobster rolls, crudo.', ARRAY['oysters', 'lobster roll', 'fish']::text[], 17, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'steak', 'Steak', 'Steak or a steakhouse cut is the draw.', ARRAY['steakhouse', 'dry-aged', 'ribeye']::text[], 18, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'dumplings', 'Dumplings', 'Dumplings of any tradition: soup dumplings, gyoza, momos, pierogi.', ARRAY['soup dumplings', 'xiao long bao', 'momos', 'gyoza']::text[], 19, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'noodles', 'Noodles', 'Asian noodle dishes other than ramen: hand-pulled, pho, pad thai, udon.', ARRAY['hand-pulled noodles', 'udon', 'pad thai']::text[], 20, 'active' FROM tag_categories WHERE slug = 'food'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'casual', 'Casual', 'Creators describe it as laid-back, no-frills or come-as-you-are.', ARRAY['laid-back', 'no-frills', 'low-key']::text[], 1, 'active' FROM tag_categories WHERE slug = 'vibe'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'upscale', 'Upscale', 'Creators describe a polished, fine-dining or special-occasion room and service.', ARRAY['fine dining', 'fancy', 'classy', 'gourmet', 'michelin']::text[], 2, 'active' FROM tag_categories WHERE slug = 'vibe'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'lively', 'Lively', 'Creators describe it as loud, buzzy, packed or high-energy.', ARRAY['buzzy', 'energetic', 'loud', 'party']::text[], 3, 'active' FROM tag_categories WHERE slug = 'vibe'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'chill', 'Chill', 'Creators describe it as relaxed and easy to hang out in for a while.', ARRAY['relaxed', 'cozy']::text[], 4, 'active' FROM tag_categories WHERE slug = 'vibe'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'romantic', 'Romantic', 'Creators call it romantic: candlelit, dim, made for two.', ARRAY['candlelit', 'sexy']::text[], 5, 'active' FROM tag_categories WHERE slug = 'vibe'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'intimate', 'Intimate', 'Creators describe a small, tucked-away or few-seats room.', ARRAY['small', 'tiny', 'hidden gem', 'tucked away']::text[], 6, 'active' FROM tag_categories WHERE slug = 'vibe'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'trendy', 'Trendy', 'Creators call it new, hyped, viral or a hard reservation.', ARRAY['hyped', 'viral', 'hot spot', 'new', 'modern']::text[], 7, 'active' FROM tag_categories WHERE slug = 'vibe'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'classic', 'Classic', 'Creators call it an institution, old-school or around for decades.', ARRAY['institution', 'old school', 'old-school', 'iconic', 'legendary']::text[], 8, 'active' FROM tag_categories WHERE slug = 'vibe'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'date_night', 'Date Night', 'Creators call it good for a date, or describe an intimate, romantic setting.', ARRAY['date spot', 'romantic dinner', 'date']::text[], 1, 'active' FROM tag_categories WHERE slug = 'occasion'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'group_hang', 'Group Hang', 'Creators say it works for a group: big tables, sharing plates, bringing friends.', ARRAY['group friendly', 'groups', 'friends', 'casual hang']::text[], 2, 'active' FROM tag_categories WHERE slug = 'occasion'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'celebration', 'Celebration', 'Creators suggest it for birthdays, anniversaries or a special occasion.', ARRAY['birthday', 'special occasion', 'anniversary']::text[], 3, 'active' FROM tag_categories WHERE slug = 'occasion'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'work_lunch', 'Work Lunch', 'Creators suggest it for a quick or business lunch.', ARRAY['lunch', 'business lunch', 'quick lunch']::text[], 4, 'active' FROM tag_categories WHERE slug = 'occasion'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'solo', 'Solo', 'Creators say it is good alone: counter seats, quick bites, a book and a coffee.', ARRAY['solo dining', 'eating alone']::text[], 5, 'active' FROM tag_categories WHERE slug = 'occasion'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'late_night', 'Late Night', 'Open late or recommended after midnight.', ARRAY['late night', 'after hours', 'open late', '2am']::text[], 6, 'active' FROM tag_categories WHERE slug = 'occasion'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'brunch', 'Brunch', 'Creators go for brunch or weekend breakfast.', ARRAY['breakfast', 'weekend brunch']::text[], 7, 'active' FROM tag_categories WHERE slug = 'occasion'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'takeout', 'Takeout', 'Creators take food to go, or it is a grab-and-go counter.', ARRAY['to go', 'grab and go', 'pickup']::text[], 1, 'active' FROM tag_categories WHERE slug = 'features'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'delivery', 'Delivery', 'Creators mention ordering delivery.', ARRAY['delivers']::text[], 2, 'active' FROM tag_categories WHERE slug = 'features'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'outdoor_seating', 'Outdoor Seating', 'Creators mention a patio, sidewalk tables, a garden or outdoor seats.', ARRAY['patio', 'outdoor', 'backyard', 'garden']::text[], 3, 'active' FROM tag_categories WHERE slug = 'features'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'rooftop', 'Rooftop', 'A rooftop bar or dining room.', ARRAY['roof', 'rooftop bar']::text[], 4, 'active' FROM tag_categories WHERE slug = 'features'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'reservations', 'Reservations', 'Creators say to book ahead or describe how to get a table.', ARRAY['book ahead', 'resy', 'hard reservation']::text[], 5, 'active' FROM tag_categories WHERE slug = 'features'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'walk_in', 'Walk-in', 'No reservations: creators say to walk in or wait in line.', ARRAY['walk-ins', 'no reservations', 'line']::text[], 6, 'active' FROM tag_categories WHERE slug = 'features'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'counter_service', 'Counter Service', 'Order at the counter rather than table service.', ARRAY['order at the counter', 'fast casual']::text[], 7, 'active' FROM tag_categories WHERE slug = 'features'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'affordable', 'Affordable', 'Creators call it cheap, a deal or good value.', ARRAY['cheap', 'cheap eats', 'budget', 'good value', 'deal']::text[], 1, 'active' FROM tag_categories WHERE slug = 'price'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'splurge', 'Splurge', 'Creators call it expensive or worth the splurge.', ARRAY['expensive', 'pricey', 'worth the splurge', '$$$$']::text[], 2, 'active' FROM tag_categories WHERE slug = 'price'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'vegetarian_friendly', 'Vegetarian-friendly', 'Creators point out good vegetarian options.', ARRAY['vegetarian', 'veggie']::text[], 1, 'active' FROM tag_categories WHERE slug = 'dietary'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'vegan', 'Vegan', 'Vegan food, or a creator points out vegan options.', ARRAY['plant-based', 'plant based']::text[], 2, 'active' FROM tag_categories WHERE slug = 'dietary'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'gluten_free', 'Gluten-free', 'Creators point out gluten-free options.', ARRAY['gf', 'celiac']::text[], 3, 'active' FROM tag_categories WHERE slug = 'dietary'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'halal', 'Halal', 'Halal food.', '{}'::text[], 4, 'active' FROM tag_categories WHERE slug = 'dietary'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;
INSERT INTO tags (category_id, slug, display_name, description, synonyms, sort_order, status)
  SELECT id, 'kosher', 'Kosher', 'Kosher food.', '{}'::text[], 5, 'active' FROM tag_categories WHERE slug = 'dietary'
  ON CONFLICT (slug) DO UPDATE SET category_id = EXCLUDED.category_id, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description, synonyms = EXCLUDED.synonyms, sort_order = EXCLUDED.sort_order, status = 'active', merged_into_id = NULL;

-- dive-bar → dive_bar
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'dive_bar') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'dive-bar')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'dive_bar'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'dive-bar');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'dive_bar') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'dive-bar')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'dive_bar'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'dive-bar');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'dive-bar');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['dive bar']) s)
  WHERE slug = 'dive_bar';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'dive_bar') WHERE slug = 'dive-bar';
-- smashburger_food → smashburger
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'smashburger') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'smashburger_food')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'smashburger'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'smashburger_food');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'smashburger') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'smashburger_food')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'smashburger'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'smashburger_food');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'smashburger_food');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['smashburger food']) s)
  WHERE slug = 'smashburger';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'smashburger') WHERE slug = 'smashburger_food';
-- birria_tacos → birria
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'birria') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'birria_tacos')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'birria'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'birria_tacos');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'birria') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'birria_tacos')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'birria'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'birria_tacos');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'birria_tacos');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['birria tacos']) s)
  WHERE slug = 'birria';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'birria') WHERE slug = 'birria_tacos';
-- expensive → splurge
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'splurge') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'expensive')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'splurge'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'expensive');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'splurge') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'expensive')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'splurge'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'expensive');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'expensive');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['expensive']) s)
  WHERE slug = 'splurge';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'splurge') WHERE slug = 'expensive';
-- pricey → splurge
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'splurge') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'pricey')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'splurge'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'pricey');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'splurge') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'pricey')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'splurge'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'pricey');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'pricey');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['pricey']) s)
  WHERE slug = 'splurge';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'splurge') WHERE slug = 'pricey';
-- cheap → affordable
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'affordable') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'cheap')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'affordable'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'cheap');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'affordable') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'cheap')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'affordable'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'cheap');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'cheap');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['cheap']) s)
  WHERE slug = 'affordable';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'affordable') WHERE slug = 'cheap';
-- casual_hang → group_hang
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'group_hang') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'casual_hang')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'group_hang'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'casual_hang');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'group_hang') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'casual_hang')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'group_hang'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'casual_hang');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'casual_hang');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['casual hang']) s)
  WHERE slug = 'group_hang';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'group_hang') WHERE slug = 'casual_hang';
-- group_friendly → group_hang
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'group_hang') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'group_friendly')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'group_hang'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'group_friendly');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'group_hang') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'group_friendly')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'group_hang'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'group_friendly');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'group_friendly');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['group friendly']) s)
  WHERE slug = 'group_hang';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'group_hang') WHERE slug = 'group_friendly';
-- classy → upscale
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'classy')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'upscale'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'classy');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'classy')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'upscale'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'classy');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'classy');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['classy']) s)
  WHERE slug = 'upscale';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE slug = 'classy';
-- gourmet → upscale
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'gourmet')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'upscale'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'gourmet');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'gourmet')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'upscale'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'gourmet');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'gourmet');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['gourmet']) s)
  WHERE slug = 'upscale';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE slug = 'gourmet';
-- michelin → upscale
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'michelin')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'upscale'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'michelin');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'michelin')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'upscale'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'michelin');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'michelin');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['michelin']) s)
  WHERE slug = 'upscale';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'upscale') WHERE slug = 'michelin';
-- modern → trendy
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'trendy') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'modern')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'trendy'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'modern');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'trendy') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'modern')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'trendy'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'modern');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'modern');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['modern']) s)
  WHERE slug = 'trendy';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'trendy') WHERE slug = 'modern';
-- old_school → classic
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'classic') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'old_school')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'classic'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'old_school');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'classic') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'old_school')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'classic'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'old_school');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'old_school');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['old school']) s)
  WHERE slug = 'classic';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'classic') WHERE slug = 'old_school';
-- dry-aged → steak
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'steak') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'dry-aged')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'steak'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'dry-aged');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'steak') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'dry-aged')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'steak'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'dry-aged');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'dry-aged');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['dry aged']) s)
  WHERE slug = 'steak';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'steak') WHERE slug = 'dry-aged';
-- detroit-style → pizza
UPDATE review_tags rt SET tag_id = (SELECT id FROM tags WHERE slug = 'pizza') WHERE rt.tag_id = (SELECT id FROM tags WHERE slug = 'detroit-style')
  AND NOT EXISTS (SELECT 1 FROM review_tags x WHERE x.review_id = rt.review_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'pizza'));
DELETE FROM review_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'detroit-style');
UPDATE place_tags pt SET tag_id = (SELECT id FROM tags WHERE slug = 'pizza') WHERE pt.tag_id = (SELECT id FROM tags WHERE slug = 'detroit-style')
  AND NOT EXISTS (SELECT 1 FROM place_tags x WHERE x.place_id = pt.place_id AND x.tag_id = (SELECT id FROM tags WHERE slug = 'pizza'));
DELETE FROM place_tags WHERE tag_id = (SELECT id FROM tags WHERE slug = 'detroit-style');
DELETE FROM place_tag_aggregates WHERE tag_id = (SELECT id FROM tags WHERE slug = 'detroit-style');
UPDATE tags SET synonyms = (SELECT array_agg(DISTINCT s) FROM unnest(synonyms || ARRAY['detroit style']) s)
  WHERE slug = 'pizza';
UPDATE tags SET status = 'deprecated', merged_into_id = (SELECT id FROM tags WHERE slug = 'pizza') WHERE slug = 'detroit-style';

UPDATE tags SET status = 'deprecated' WHERE status = 'active' AND slug NOT IN ('restaurant', 'bar', 'cocktail_bar', 'wine_bar', 'dive_bar', 'cafe', 'bakery', 'deli', 'food_hall', 'dessert_shop', 'american', 'italian', 'mexican', 'japanese', 'chinese', 'korean', 'thai', 'vietnamese', 'indian', 'mediterranean', 'middle_eastern', 'french', 'caribbean', 'latin_american', 'jewish_deli', 'burger', 'smashburger', 'pizza', 'pasta', 'tacos', 'birria', 'ramen', 'sushi', 'wings', 'bbq', 'sandwich', 'bagels', 'coffee', 'pastries', 'dessert', 'ice_cream', 'seafood', 'steak', 'dumplings', 'noodles', 'casual', 'upscale', 'lively', 'chill', 'romantic', 'intimate', 'trendy', 'classic', 'date_night', 'group_hang', 'celebration', 'work_lunch', 'solo', 'late_night', 'brunch', 'takeout', 'delivery', 'outdoor_seating', 'rooftop', 'reservations', 'walk_in', 'counter_service', 'affordable', 'splurge', 'vegetarian_friendly', 'vegan', 'gluten_free', 'halal', 'kosher');

-- The 31 'manual' place tags came from a seed script that assigned tags at random;
-- they are not admin overrides.
UPDATE place_tags SET source = 'ai' WHERE source = 'manual';
