/**
 * Seeds the four agents and their v1 versions from
 * src/lib/engine/agents/<key>/prompt.v1.md. After the seed the database is
 * the source of truth for prompts (edited on the Agents page).
 *
 *   npx tsx scripts/agents-v1.ts > prisma/migrations/0005_agents_v1/migration.sql
 *
 * The names here are the v1 seed's; 0009_product_names renamed the agents
 * (Post reader, Place finder, Tagger, Summary writer).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

export const AGENTS_V1 = [
  {
    key: "read",
    name: "Read",
    description: "Reads a post and reports every place it mentions, with an excerpt, dishes, verdict and score for each.",
    model: "claude-sonnet-5",
    effort: "low",
    maxTokens: 4000,
  },
  {
    key: "resolve",
    name: "Resolve",
    description: "Picks the Google listing a mentioned place refers to when code isn't sure.",
    model: "claude-sonnet-5",
    effort: "low",
    maxTokens: 1000,
  },
  {
    key: "tag",
    name: "Tag",
    description: "Tags one mention from the taxonomy, quoting the evidence for each tag.",
    model: "claude-haiku-4-5",
    effort: null,
    maxTokens: 1500,
  },
  {
    key: "summarize",
    name: "Summarize",
    description: "Writes a place's summary and known-for dishes from its mentions.",
    model: "claude-sonnet-5",
    effort: "low",
    maxTokens: 800,
  },
] as const;

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const dollar = (s: string) => {
  if (s.includes("$prompt$")) throw new Error("prompt contains the dollar-quote tag");
  return `$prompt$${s}$prompt$`;
};

function sql(): string {
  const out = ["-- Agents and their v1 prompts: generated by scripts/agents-v1.ts. Data only.", ""];
  for (const a of AGENTS_V1) {
    const prompt = readFileSync(join("src/lib/engine/agents", a.key, "prompt.v1.md"), "utf8").trim();
    out.push(
      `INSERT INTO "agents" ("key", "name", "description") VALUES (${q(a.key)}, ${q(a.name)}, ${q(a.description)})`,
      `  ON CONFLICT ("key") DO NOTHING;`,
      `INSERT INTO "agent_versions" ("agent_key", "version", "system_prompt", "model", "effort", "max_tokens", "notes", "status", "created_by")`,
      `  VALUES (${q(a.key)}, 1, ${dollar(prompt)}, ${q(a.model)}, ${a.effort ? q(a.effort) : "NULL"}, ${a.maxTokens}, 'v1, from the engine spec', 'active', 'seed')`,
      `  ON CONFLICT ("agent_key", "version") DO NOTHING;`,
      "",
    );
  }
  out.push(
    `UPDATE "agents" a SET "active_version_id" = v."id"`,
    `  FROM "agent_versions" v`,
    ` WHERE v."agent_key" = a."key" AND v."version" = 1 AND a."active_version_id" IS NULL;`,
    "",
  );
  return out.join("\n");
}

if (process.argv[1]?.endsWith("agents-v1.ts")) process.stdout.write(sql());
